### ISSUE TITLE
Analyze what needs to be improved

### ISSUE THREAD

**Issue by m-ke** [cre-project/pdf-app#1]
- Go over the template to see what needs to be fixed / improved
- Make sure all values from the dashboard are displayed and correct
- Check what happens if data is missing or if there are too many rows
- Check what needs to be adapted for this to work with the backend
- See if it's possible to have multiple colors to choose from for the template (css variables)

**Comment by Sjefkesuit** [comment]
1 additional thing would be to see if there is an somewhat easy option to add an empty page (with simply lay out, we can make an example). But so that that way user can include those and offline in a pdf editor add text fields or other things to their liking.

This would be a great way to solve for the fact that we only support limited content at first as it would give the users the ability to add whatever content they like to the package.

**Comment by marionschleifer** [comment]
Made a follow-up issue for this (as agreed): https://github.com/cre-project/pdf-app/issues/8
Some points need discussion.
