### ISSUE TITLE
Google maps API integration

### ISSUE THREAD

**Issue by m-ke** [cre-project/pdf-app#2]
Add integration with google maps static API with pins for the current property & comparables
API key for google maps is in lastpass

**Comment by marionschleifer** [comment]
@m-ke @Sjefkesuit We have a problem with the Google maps API. It looks like this:

![image](https://user-images.githubusercontent.com/5722022/51143285-7753b100-184e-11e9-8dcb-1e7dce096257.png)

When I researched it, it says that something about enabling billing: https://stackoverflow.com/questions/50977913/google-maps-shows-for-development-purposes-only.

**Comment by m-ke** [comment]
Let's add it to the list for tomorrow evening :)

**Comment by marionschleifer** [comment]
Yes :)

Here are the error messages:

![image](https://user-images.githubusercontent.com/5722022/51144218-ba168880-1850-11e9-94d4-7dc8b3d21aaa.png)

**Comment by marionschleifer** [comment]
Also, as we need to include the map twice, I get this error:

![image](https://user-images.githubusercontent.com/5722022/51144673-06ae9380-1852-11e9-871c-0d821078c412.png)

Maybe, we'll find away to work around this...

**Comment by sjeftijssen** [comment]
@marionschleifer I went ahead and set up a new API Key. I will share with you on slack directly. Please use that one instead of the one from yesterday. I am not 100% sure how google does this but this is the one from at least the MAP javascript. If we need others, can you let me know from this list: [https://console.cloud.google.com/apis/library](https://console.cloud.google.com/apis/library).

If none of this works we can have a look tonight

**Comment by marionschleifer** [comment]
TODO:
- [ ] Add api key as environment variable
- [ ] Get address instead of long/lat
- [ ] Use real data and fill variables in PDF app

**Comment by m-ke** [comment]
Please use a node library for the google maps rather than the client side
url https://github.com/googlemaps/google-maps-services-js

**Comment by m-ke** [comment]
(also will make it easier to add the API key into the right place -
initialize the google maps in app.js and then import in maps.js)
